version: "3.8"

services:

  server:
    image: azoff/flask-pdf-tokenizer
    build:
      context: .
      target: local
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: /app
